<a href="https://colab.research.google.com/github/codemaster-omvardhan/ML-projects/blob/main/PyTorch_TrainingPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
from google.colab import files
uploaded = files.upload()

Saving breast-cancer.csv to breast-cancer.csv


In [3]:
df = pd.read_csv('breast-cancer.csv')

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [5]:
df.shape

(569, 32)

In [6]:
df.drop(columns=['id'], inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [9]:
scaler = StandardScaler()

In [10]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 0.94549852,  4.57085111,  0.88116186, ...,  1.44810602,
        -0.05704226,  0.10357485],
       [ 1.38531783, -0.10028863,  1.29448739, ...,  0.1288588 ,
        -0.07719305, -1.08451002],
       [-0.56245338, -0.34565532, -0.59069031, ..., -0.85093118,
        -1.10824215, -0.57706712],
       ...,
       [ 1.80514534,  0.30330518,  1.76154522, ...,  0.74336665,
         0.55923628, -1.17870601],
       [-0.45963848, -0.29291295, -0.52331826, ..., -1.51164379,
        -1.09816675, -1.70438039],
       [-0.59958098, -1.0817554 , -0.58035718, ..., -0.74732049,
        -0.23504096, -0.01492978]])

In [12]:
y_train

,diagnosis
239,M
127,M
96,B
134,M
541,B
...,...
265,M
248,B
533,M
360,B


In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,

**Numpy arrays to PyTorch tensors**


In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [19]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [32]:
class MySimpleNN:
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #Calculate loss
    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

**Important Parameters**

In [37]:
learning_rate = 0.1
epochs = 25

**Training Pipeline**

In [38]:
#create model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)
  print(y_pred)

  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

  #backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')



Streaming output truncated to the last 5000 lines.
        [0.4330],
        [0.9144],
        [0.9612],
        [0.0241],
        [1.0000],
        [0.0131],
        [0.7757],
        [0.8923],
        [0.3338],
        [0.1069],
        [0.0208],
        [0.9701],
        [0.0346],
        [0.0208],
        [0.9979],
        [0.0734],
        [0.0657],
        [0.1432],
        [0.0801],
        [0.0434],
        [0.9980],
        [0.7428],
        [0.7236],
        [0.9804],
        [0.0369],
        [0.0400],
        [0.0434],
        [0.0939],
        [0.9318],
        [0.9835],
        [0.2584],
        [0.9845],
        [0.1774],
        [0.4360],
        [0.9999],
        [0.0246],
        [0.0498],
        [0.9986],
        [0.0187],
        [0.1495],
        [0.9957],
        [0.8658],
        [0.9731],
        [0.1177],
        [0.6451],
        [0.1566],
        [0.9417],
        [0.9915],
        [0.0116],
        [0.9969],
        [0.1743],
        [0.2812],
        [0.71

In [39]:
model.weights

tensor([[ 0.0429],
        [ 0.1699],
        [-0.2634],
        [-0.0718],
        [-0.3556],
        [ 0.2262],
        [ 0.2904],
        [-0.5390],
        [ 0.2235],
        [-0.0940],
        [ 0.2355],
        [ 0.0762],
        [ 0.0399],
        [ 0.2956],
        [ 0.7254],
        [ 0.3262],
        [ 0.0777],
        [-0.1778],
        [ 0.1720],
        [-0.3187],
        [ 0.2679],
        [ 0.1012],
        [-0.2169],
        [-0.0708],
        [ 0.1177],
        [-0.2775],
        [ 0.1402],
        [ 0.0579],
        [ 0.2515],
        [-0.0631]], dtype=torch.float64, requires_grad=True)

In [40]:
model.bias

tensor([-0.1399], dtype=torch.float64, requires_grad=True)

**Evaluation**

In [46]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5846414566040039
